(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


module Stdlib_en
  = Stdlib_en
module Date_en = Date_en
module MonthYear_en = MonthYear_en
module Period_en = Period_en
module Money_en = Money_en
module Integer_en = Integer_en
module Decimal_en = Decimal_en
module List_en = List_en

module FilingStatus : sig
  type t =
    | JointReturn
    | SurvivingSpouse
    | HeadOfHousehold
    | Single
    | MarriedFilingSeparately
end

module ResidencyStatus : sig type t = Resident | NonresidentAlien end

module DecreeType : sig type t = Divorce | SeparateMaintenance end

module ParentType : sig type t = Biological | Step | Adoptive end

module FamilyRelationshipType : sig
  type t =
    | Child
    | DescendantOfChild
    | Brother
    | Sister
    | Stepbrother
    | Stepsister
    | DescendantOfSibling
    | Father
    | Mother
    | AncestorOfFatherOrMother
    | Stepfather
    | Stepmother
    | NieceOrNephew
    | UncleOrAunt
    | SonInLaw
    | DaughterInLaw
    | FatherInLaw
    | MotherInLaw
    | BrotherInLaw
    | SisterInLaw
end

module OrganizationType : sig
  type t =
    | Business
    | GovernmentFederal
    | GovernmentState
    | EducationalInstitution
    | Hospital
    | Club
    | FraternityOrSorority
    | ForeignGovernment
    | InternationalOrganization
    | PenalInstitution
end

module EmploymentCategory : sig
  type t =
    | General
    | AgriculturalLabor
    | DomesticService
    | FederalGovernment
    | StateGovernment
    | SchoolCollegeUniversity
    | Hospital
    | ForeignGovernment
    | InternationalOrganization
    | PenalInstitution
end

module ServiceLocation : sig
  type t = WithinUnitedStates | OutsideUnitedStates
end

module PaymentMedium : sig type t = Cash | NonCash end

module PaymentReason : sig
  type t =
    | RegularCompensation
    | SicknessOrAccidentDisability
    | Death
    | TerminationAfterDeathOrDisabilityRetirement
    | AgriculturalLaborNonCash
    | DomesticServiceNonBusiness
end

module VisaCategory : sig type t = H2A | Other end

module TerminationReason : sig
  type t = Death | DisabilityRetirement | Other
end

module Individual : sig
  type t = {id: integer; is_counterfactual: bool}
end

module Household : sig
  type t = {id: integer; is_counterfactual: bool}
end

module Organization : sig
  type t = {
    id: integer;
    organization_type: OrganizationType.t;
    is_counterfactual: bool
  }
end

module IndividualSection7703MaritalStatusOutput : sig
  type t = {
    individual: Individual.t;
    tax_year: integer;
    determination_date_7703_a_1: date;
    is_married_7703_a_1: bool;
    is_legally_separated_7703_a_2: bool;
    maintains_household_7703_b_1: bool;
    furnishes_over_one_half_cost_7703_b_2: bool;
    spouse_not_member_last_6_months_7703_b_3:
      bool;
    considered_not_married_7703_b: bool;
    is_married_for_tax_purposes_7703: bool
  }
end

module IndividualSection152QualifyingRelativeOutput : sig
  type t = {
    individual: Individual.t;
    taxpayer: Individual.t;
    is_qualifying_relative: bool;
    is_household_member_152_d_2_H: bool;
    bears_relationship_152_d_1_A: bool;
    has_no_income_152_d_1_B: bool;
    is_not_qualifying_child_152_d_1_D: bool
  }
end

module IndividualSection152QualifyingChildOutput : sig
  type t = {
    individual: Individual.t;
    taxpayer: Individual.t;
    is_qualifying_child: bool;
    bears_relationship_152_c_1_A: bool;
    has_same_principal_place_of_abode_152_c_1_B:
      bool;
    meets_age_requirements_152_c_1_C: bool;
    has_not_filed_joint_return_152_c_1_E: bool
  }
end

module IndividualDependentStatus : sig
  type t = {
    individual: Individual.t;
    is_qualifying_child: bool;
    is_qualifying_relative: bool;
    is_excepted_under_152_b_2: bool;
    is_ineligible_under_152_b_1: bool
  }
end

module IndividualSection151PersonalExemptionOutput : sig
  type t = {
    individual: Individual.t;
    exemption_amount_base: money;
    exemption_amount_after_disallowance: money;
    exemption_amount_after_phaseout: money;
    personal_exemptions_deduction_151_a: money;
    applicable_percentage_151_d_3_B: decimal;
    exemption_amount_zero_151_d_5: bool
  }
end

module IndividualSection151ExemptionsListOutput : sig
  type t = {
    individual: Individual.t;
    spouse_exemption_allowed_151_b: bool;
    individuals_entitled_to_exemptions_under_151:
      Individual.t array
  }
end

module ImmigrationAdmissionEvent : sig
  type t = {
    id: integer;
    individual: Individual.t;
    visa_category: VisaCategory.t;
    admission_date: date;
    is_counterfactual: bool
  }
end

module TaxReturnEvent : sig
  type t = {
    id: integer;
    individual: Individual.t;
    tax_year: integer;
    filed_joint_return: bool;
    is_only_for_refund_claim: bool;
    qualifying_children: Individual.t array;
    dependents: Individual.t array;
    is_counterfactual: bool
  }
end

module IncomeEvent : sig
  type t = {
    id: integer;
    individual: Individual.t;
    tax_year: integer;
    has_income: bool;
    earned_income: money;
    is_counterfactual: bool
  }
end

module FamilyRelationshipEvent : sig
  type t = {
    id: integer;
    person: Individual.t;
    relative: Individual.t;
    start_date: date;
    relationship_type: FamilyRelationshipType.t;
    is_counterfactual: bool
  }
end

module ParenthoodEvent : sig
  type t = {
    id: integer;
    parent: Individual.t;
    child: Individual.t;
    start_date: date;
    parent_type: ParentType.t;
    is_counterfactual: bool
  }
end

module DivorceOrLegalSeparationEvent : sig
  type t = {
    id: integer;
    person1: Individual.t;
    person2: Individual.t;
    decree_date: date;
    decree_type: DecreeType.t;
    is_counterfactual: bool
  }
end

module RemarriageEvent : sig
  type t = {
    id: integer;
    individual: Individual.t;
    remarriage_date: date;
    is_counterfactual: bool
  }
end

module MarriageEvent : sig
  type t = {
    id: integer;
    spouse1: Individual.t;
    spouse2: Individual.t;
    marriage_date: date;
    is_counterfactual: bool
  }
end

module MarriedFilingSeparateVariant : sig
  type t = {
    taxpayer: Individual.t;
    spouse: Individual.t;
    itemization_election: bool;
    spouse_itemization_election: bool;
    is_estate_or_trust: bool;
    is_common_trust_fund: bool;
    is_partnership: bool
  }
end

module SingleVariant : sig
  type t = {
    taxpayer: Individual.t;
    itemization_election: bool;
    is_estate_or_trust: bool;
    is_common_trust_fund: bool;
    is_partnership: bool
  }
end

module HeadOfHouseholdVariant : sig
  type t = {
    taxpayer: Individual.t;
    qualifying_person: Individual.t;
    itemization_election: bool;
    is_estate_or_trust: bool;
    is_common_trust_fund: bool;
    is_partnership: bool
  }
end

module SurvivingSpouseVariant : sig
  type t = {
    taxpayer: Individual.t;
    deceased_spouse: Individual.t;
    qualifying_dependent: Individual.t;
    itemization_election: bool;
    is_estate_or_trust: bool;
    is_common_trust_fund: bool;
    is_partnership: bool
  }
end

module JointReturnVariant : sig
  type t = {
    taxpayer: Individual.t;
    spouse: Individual.t;
    itemization_election: bool;
    is_estate_or_trust: bool;
    is_common_trust_fund: bool;
    is_partnership: bool
  }
end

module NonresidentAlienStatusPeriodEvent : sig
  type t = {
    id: integer;
    individual: Individual.t;
    start_date: date;
    end_date: date;
    residency_status: ResidencyStatus.t;
    is_counterfactual: bool
  }
end

module DeathEvent : sig
  type t = {
    id: integer;
    decedent: Individual.t;
    death_date: date;
    is_counterfactual: bool
  }
end

module BlindnessStatusEvent : sig
  type t = {
    id: integer;
    individual: Individual.t;
    status_date: date;
    is_blind: bool;
    is_counterfactual: bool
  }
end

module BirthEvent : sig
  type t = {
    id: integer;
    individual: Individual.t;
    birth_date: date;
    is_counterfactual: bool
  }
end

module HouseholdMaintenanceEvent : sig
  type t = {
    id: integer;
    individual: Individual.t;
    household: Household.t;
    start_date: date;
    end_date: date;
    cost_furnished_percentage: decimal;
    is_counterfactual: bool
  }
end

module ResidencePeriodEvent : sig
  type t = {
    id: integer;
    individual: Individual.t;
    household: Household.t;
    start_date: date;
    end_date: date;
    is_member_of_household: bool;
    is_principal_place_of_abode: bool;
    is_counterfactual: bool
  }
end

module OrganizationSection3306EmployerStatusOutput : sig
  type t = {
    organization: Organization.t;
    is_employer: bool;
    is_general_employer: bool;
    is_agricultural_employer: bool;
    is_domestic_service_employer: bool
  }
end

module EmployerDomesticServiceVariant : sig
  type t = {employer: Organization.t}
end

module EmployerAgriculturalLaborVariant : sig
  type t = {employer: Organization.t}
end

module EmployerGeneralVariant : sig
  type t = {employer: Organization.t}
end

module EmploymentTerminationEvent : sig
  type t = {
    id: integer;
    employer: Organization.t;
    employee: Individual.t;
    termination_date: date;
    reason: TerminationReason.t;
    is_counterfactual: bool
  }
end

module HospitalPatientEvent : sig
  type t = {
    id: integer;
    patient: Individual.t;
    hospital: Organization.t;
    start_date: date;
    end_date: date;
    is_counterfactual: bool
  }
end

module StudentEnrollmentEvent : sig
  type t = {
    id: integer;
    student: Individual.t;
    institution: Organization.t;
    start_date: date;
    end_date: date;
    is_regularly_attending: bool;
    is_counterfactual: bool
  }
end

module WagePaymentEvent : sig
  type t = {
    id: integer;
    employer: Organization.t;
    employee: Individual.t;
    payment_date: date;
    amount: money;
    payment_medium: PaymentMedium.t;
    payment_reason: PaymentReason.t;
    is_under_plan_or_system: bool;
    is_for_employee_generally: bool;
    is_for_class_of_employees: bool;
    is_for_dependents: bool;
    is_not_in_course_of_trade_or_business: bool;
    would_have_been_paid_without_termination:
      bool;
    is_paid_to_survivor_or_estate: bool;
    is_counterfactual: bool
  }
end

module EmploymentRelationshipEvent : sig
  type t = {
    id: integer;
    employer: Organization.t;
    employee: Individual.t;
    start_date: date;
    end_date: date;
    employment_category: EmploymentCategory.t;
    service_location: ServiceLocation.t;
    is_american_employer: bool;
    employee_is_us_citizen: bool;
    is_counterfactual: bool
  }
end

module IndividualSection7703MaritalStatus : sig
  type t = {
    main_output:
      IndividualSection7703MaritalStatusOutput.t
  }
end

module IndividualSection152QualifyingRelative : sig
  type t = {
    main_output:
      IndividualSection152QualifyingRelativeOutput.t
  }
end

module IndividualSection152QualifyingChild : sig
  type t = {
    main_output:
      IndividualSection152QualifyingChildOutput.t
  }
end

module IndividualSection152DependentsOutput : sig
  type t = {
    taxpayer: Individual.t;
    dependents_initial: Individual.t array;
    dependents_after_152b1: Individual.t array;
    dependents_after_152b2: Individual.t array;
    qualifying_children:
      IndividualSection152QualifyingChildOutput.t
      array;
    qualifying_relatives:
      IndividualSection152QualifyingRelativeOutput.t
      array;
    individual_dependent_statuses:
      IndividualDependentStatus.t array
  }
end

module IndividualSection151PersonalExemption : sig
  type t = {
    main_output:
      IndividualSection151PersonalExemptionOutput.t
  }
end

module IndividualSection151ExemptionsList : sig
  type t = {
    main_output:
      IndividualSection151ExemptionsListOutput.t
  }
end

module TaxpayerExemptionsList151Output : sig
  type t = {
    taxpayer_result:
      IndividualSection151ExemptionsListOutput.t;
    spouse_result:
      (IndividualSection151ExemptionsListOutput.t) Optional.t;
    individuals_entitled_to_exemptions_under_151:
      Individual.t array;
    spouse_exemption_allowed_151_b: bool
  }
end

module FilingStatusVariant : sig
  type t =
    | JointReturn of JointReturnVariant.t
    | SurvivingSpouse of SurvivingSpouseVariant.t
    | HeadOfHousehold of HeadOfHouseholdVariant.t
    | Single of SingleVariant.t
    | MarriedFilingSeparate of
        MarriedFilingSeparateVariant.t
end

module OrganizationSection3306EmployerStatus : sig
  type t = {
    main_output:
      OrganizationSection3306EmployerStatusOutput.t
  }
end

module EmployerVariant : sig
  type t =
    | GeneralEmployer of EmployerGeneralVariant.t
    | AgriculturalEmployer of
        EmployerAgriculturalLaborVariant.t
    | DomesticServiceEmployer of
        EmployerDomesticServiceVariant.t
end

module WagePaymentEventSection3306WagesOutput : sig
  type t = {
    wage_payment_event: WagePaymentEvent.t;
    is_excluded_by_sickness_disability_death:
      bool;
    is_excluded_by_nonbusiness_service: bool;
    is_excluded_by_termination_payment: bool;
    is_excluded_by_agricultural_noncash: bool;
    is_excluded_by_survivor_payment: bool;
    taxable_amount_before_7000_cap: money
  }
end

module EmploymentRelationshipEventSection3306EmploymentOutput : sig
  type t = {
    employment_relationship_event:
      EmploymentRelationshipEvent.t;
    is_employment: bool;
    is_excluded_agricultural_labor: bool;
    is_excluded_domestic_service: bool;
    is_excluded_family_employment: bool;
    is_excluded_federal_government: bool;
    is_excluded_state_government: bool;
    is_excluded_student_service: bool;
    is_excluded_hospital_patient_service: bool;
    is_excluded_foreign_government: bool;
    is_excluded_student_nurse: bool;
    is_excluded_international_organization: bool;
    is_excluded_penal_institution: bool
  }
end

module IndividualSection152Dependents : sig
  type t = {
    main_output:
      IndividualSection152DependentsOutput.t
  }
end

module TaxpayerExemptionsList151 : sig
  type t = {
    main_output:
      TaxpayerExemptionsList151Output.t
  }
end

module IndividualTaxReturn : sig
  type t = {
    id: integer;
    tax_year: integer;
    details: FilingStatusVariant.t
  }
end

module EmployerUnemploymentExciseTaxReturn : sig
  type t = {
    id: integer;
    tax_year: integer;
    details: EmployerVariant.t
  }
end

module WagePaymentEventSection3306Wages : sig
  type t = {
    main_output:
      WagePaymentEventSection3306WagesOutput.t
  }
end

module TotalWages3306CalculationOutput : sig
  type t = {
    total_taxable_wages: money;
    wage_results_with_cap:
      WagePaymentEventSection3306WagesOutput.t
      array
  }
end

module EmploymentRelationshipEventSection3306Employment : sig
  type t = {
    main_output:
      EmploymentRelationshipEventSection3306EmploymentOutput.t
  }
end

module IndividualTaxReturnSection68ItemizedDeductionsOutput : sig
  type t = {
    individual_tax_return: IndividualTaxReturn.t;
    applicable_amount_68_b_1: money;
    three_percent_reduction_68_a_1: money;
    eighty_percent_reduction_68_a_2: money;
    reduction_amount_68_a: money;
    itemized_deductions_after_68: money;
    section_not_applicable_68_f: bool
  }
end

module IndividualTaxReturnSection63TaxableIncomeOutput : sig
  type t = {
    individual_tax_return: IndividualTaxReturn.t;
    taxable_income: money;
    standard_deduction_63_c_1: money;
    standard_deduction_eligible_63_c_6: bool;
    basic_standard_deduction_63_c_2_before_c_5:
      money;
    basic_standard_deduction_63_c_2_after_c_5:
      money;
    additional_standard_deduction_63_c_3: money;
    additional_amount_taxpayer_aged_63_f_1_A:
      money;
    additional_amount_spouse_aged_63_f_1_B: money;
    additional_amount_taxpayer_blind_63_f_2_A:
      money;
    additional_amount_spouse_blind_63_f_2_B:
      money
  }
end

module IndividualTaxReturnSection2bHeadOfHouseholdOutput : sig
  type t = {
    individual_tax_return: IndividualTaxReturn.t;
    is_legally_separated_2_b_2_A: bool;
    spouse_is_nonresident_alien_2_b_2_B: bool;
    spouse_died_during_year_2_b_2_C: bool;
    is_married_at_year_end_2_b_2: bool;
    taxpayer_is_nonresident_alien_2_b_3_A: bool;
    head_of_household_disqualified_household_member_dependent_2_b_3_B:
      bool;
    is_married_at_year_end_2_b_1_A_i_I: bool;
    is_not_dependent_by_152b2_2_b_1_A_i_II: bool;
    qualifying_child_meets_2_b_1_A_i: bool;
    other_dependent_2_b_1_A_ii: bool;
    maintains_household_principal_place_of_abode_more_than_half_year_2_b_1_A:
      bool;
    maintains_household_for_father_or_mother_2_b_1_B:
      bool;
    is_head_of_household_2_b: bool
  }
end

module IndividualTaxReturnSection2aSurvivingSpouseOutput : sig
  type t = {
    individual_tax_return: IndividualTaxReturn.t;
    spouse_died_within_two_years_2_a_1_A: bool;
    maintains_household_qualifying_dependent_principal_abode_section151_2_a_1_B:
      bool;
    has_remarried_2_a_2_A: bool;
    joint_return_could_have_been_made_2_a_2_B:
      bool;
    is_surviving_spouse_2_a: bool
  }
end

module IndividualTaxReturnSection1TaxOutput : sig
  type t = {
    individual_tax_return: IndividualTaxReturn.t;
    tax_1_a_1: money;
    tax_1_a_2: money;
    tax_1_b: money;
    tax_1_c: money;
    tax_1_d: money;
    tax: money
  }
end

module EmployerUnemploymentExciseTaxFilerSection3301TaxOutput : sig
  type t = {
    employer_unemployment_excise_tax_return:
      EmployerUnemploymentExciseTaxReturn.t;
    total_taxable_wages: money;
    excise_tax: money;
    tax_rate: decimal
  }
end

module TotalWages3306Calculation : sig
  type t = {
    main_output:
      TotalWages3306CalculationOutput.t
  }
end

module IndividualTaxReturnSection68ItemizedDeductions : sig
  type t = {
    main_output:
      IndividualTaxReturnSection68ItemizedDeductionsOutput.t
  }
end

module IndividualTaxReturnSection63TaxableIncome : sig
  type t = {
    main_output:
      IndividualTaxReturnSection63TaxableIncomeOutput.t
  }
end

module IndividualTaxReturnSection2bHeadOfHousehold : sig
  type t = {
    main_output:
      IndividualTaxReturnSection2bHeadOfHouseholdOutput.t
  }
end

module IndividualTaxReturnSection2aSurvivingSpouse : sig
  type t = {
    main_output:
      IndividualTaxReturnSection2aSurvivingSpouseOutput.t
  }
end

module IndividualTaxReturnSection1Tax : sig
  type t = {
    main_output:
      IndividualTaxReturnSection1TaxOutput.t
  }
end

module IRCSimplified : sig
  type t = {
    taxable_income: money;
    itemized_deductions: money;
    adjusted_gross_income: money;
    taxable_income_result:
      IndividualTaxReturnSection63TaxableIncomeOutput.t;
    tax: money;
    is_surviving_spouse: bool;
    is_head_of_household: bool;
    section_2a_surviving_spouse_result:
      IndividualTaxReturnSection2aSurvivingSpouseOutput.t;
    section_2b_head_of_household_result:
      IndividualTaxReturnSection2bHeadOfHouseholdOutput.t;
    itemized_deductions_result:
      IndividualTaxReturnSection68ItemizedDeductionsOutput.t;
    taxpayer_exemptions_list_result:
      TaxpayerExemptionsList151Output.t;
    taxpayer_exemption_result:
      IndividualSection151PersonalExemptionOutput.t;
    tax_imposed_result:
      IndividualTaxReturnSection1TaxOutput.t;
    taxpayer_dependents_result:
      IndividualSection152DependentsOutput.t;
    taxpayer_marital_status_7703:
      IndividualSection7703MaritalStatusOutput.t;
    organization_employer_statuses:
      OrganizationSection3306EmployerStatusOutput.t
      array;
    wage_payment_wages_results:
      WagePaymentEventSection3306WagesOutput.t
      array;
    employment_relationship_employment_results:
      EmploymentRelationshipEventSection3306EmploymentOutput.t
      array;
    employer_unemployment_excise_tax_result:
      EmployerUnemploymentExciseTaxFilerSection3301TaxOutput.t
  }
end

module EmployerUnemploymentExciseTaxFilerSection3301Tax : sig
  type t = {
    total_taxable_wages: money;
    excise_tax: money;
    tax_rate: decimal;
    main_output:
      EmployerUnemploymentExciseTaxFilerSection3301TaxOutput.t
  }
end

module IndividualTaxReturnSection1Tax_in : sig
  type t = {
    individual_tax_return_in:
      IndividualTaxReturn.t;
    taxable_income_in: money;
    taxpayer_marital_status_in:
      IndividualSection7703MaritalStatusOutput.t;
    is_surviving_spouse_in: bool;
    is_head_of_household_in: bool;
    tax_1_a_1_in:
      ((money * code_location)) Optional.t;
    tax_1_a_2_in:
      ((money * code_location)) Optional.t;
    tax_1_b_in:
      ((money * code_location)) Optional.t;
    tax_1_c_in:
      ((money * code_location)) Optional.t;
    tax_1_d_in:
      ((money * code_location)) Optional.t;
    tax_in: ((money * code_location)) Optional.t
  }
end

module IndividualTaxReturnSection2aSurvivingSpouse_in : sig
  type t = {
    individual_tax_return_in:
      IndividualTaxReturn.t;
    death_events_in: DeathEvent.t array;
    nonresident_alien_status_period_events_in:
      NonresidentAlienStatusPeriodEvent.t array;
    parenthood_events_in: ParenthoodEvent.t array;
    household_maintenance_events_in:
      HouseholdMaintenanceEvent.t array;
    residence_period_events_in:
      ResidencePeriodEvent.t array;
    marriage_events_in: MarriageEvent.t array;
    taxpayer_exemptions_list_result_in:
      TaxpayerExemptionsList151Output.t;
    spouse_died_within_two_years_2_a_1_A_in:
      ((bool * code_location)) Optional.t;
    maintains_household_qualifying_dependent_principal_abode_section151_2_a_1_B_in:
      ((bool * code_location)) Optional.t;
    has_remarried_2_a_2_A_in:
      ((bool * code_location)) Optional.t;
    joint_return_could_have_been_made_2_a_2_B_in:
      ((bool * code_location)) Optional.t;
    is_surviving_spouse_2_a_in:
      ((bool * code_location)) Optional.t
  }
end

module IndividualTaxReturnSection2bHeadOfHousehold_in : sig
  type t = {
    individual_tax_return_in:
      IndividualTaxReturn.t;
    nonresident_alien_status_period_events_in:
      NonresidentAlienStatusPeriodEvent.t array;
    parenthood_events_in: ParenthoodEvent.t array;
    household_maintenance_events_in:
      HouseholdMaintenanceEvent.t array;
    residence_period_events_in:
      ResidencePeriodEvent.t array;
    marriage_events_in: MarriageEvent.t array;
    divorce_or_legal_separation_events_in:
      DivorceOrLegalSeparationEvent.t array;
    family_relationship_events_in:
      FamilyRelationshipEvent.t array;
    birth_events_in: BirthEvent.t array;
    tax_return_events_in: TaxReturnEvent.t array;
    taxpayer_exemptions_list_result_in:
      TaxpayerExemptionsList151Output.t;
    taxpayer_dependents_result_in:
      IndividualSection152DependentsOutput.t;
    death_events_in: DeathEvent.t array;
    is_surviving_spouse_2_a_in: bool;
    qualifying_person_qualifying_child_result_in:
      (((IndividualSection152QualifyingChildOutput.t) Optional.t
         * code_location)) Optional.t;
    is_legally_separated_2_b_2_A_in:
      ((bool * code_location)) Optional.t;
    spouse_is_nonresident_alien_2_b_2_B_in:
      ((bool * code_location)) Optional.t;
    spouse_died_during_year_2_b_2_C_in:
      ((bool * code_location)) Optional.t;
    is_married_at_year_end_2_b_2_in:
      ((bool * code_location)) Optional.t;
    taxpayer_is_nonresident_alien_2_b_3_A_in:
      ((bool * code_location)) Optional.t;
    head_of_household_disqualified_household_member_dependent_2_b_3_B_in:
      ((bool * code_location)) Optional.t;
    is_married_at_year_end_2_b_1_A_i_I_in:
      ((bool * code_location)) Optional.t;
    is_not_dependent_by_152b2_2_b_1_A_i_II_in:
      ((bool * code_location)) Optional.t;
    qualifying_child_meets_2_b_1_A_i_in:
      ((bool * code_location)) Optional.t;
    other_dependent_2_b_1_A_ii_in:
      ((bool * code_location)) Optional.t;
    maintains_household_principal_place_of_abode_more_than_half_year_2_b_1_A_in:
      ((bool * code_location)) Optional.t;
    maintains_household_for_father_or_mother_2_b_1_B_in:
      ((bool * code_location)) Optional.t;
    is_head_of_household_2_b_in:
      ((bool * code_location)) Optional.t
  }
end

module IndividualTaxReturnSection63TaxableIncome_in : sig
  type t = {
    individual_tax_return_in:
      IndividualTaxReturn.t;
    birth_events_in: BirthEvent.t array;
    blindness_status_events_in:
      BlindnessStatusEvent.t array;
    death_events_in: DeathEvent.t array;
    income_events_in: IncomeEvent.t array;
    tax_return_events_in: TaxReturnEvent.t array;
    nonresident_alien_status_period_events_in:
      NonresidentAlienStatusPeriodEvent.t array;
    taxpayer_marital_status_in:
      IndividualSection7703MaritalStatusOutput.t;
    is_surviving_spouse_in: bool;
    is_head_of_household_in: bool;
    taxpayer_exemptions_list_result_in:
      TaxpayerExemptionsList151Output.t;
    taxpayer_exemption_result_in:
      IndividualSection151PersonalExemptionOutput.t;
    adjusted_gross_income_in: money;
    itemized_deductions_result_in:
      IndividualTaxReturnSection68ItemizedDeductionsOutput.t;
    additional_amount_taxpayer_aged_63_f_1_A_in:
      ((money * code_location)) Optional.t;
    additional_amount_spouse_aged_63_f_1_B_in:
      ((money * code_location)) Optional.t;
    additional_amount_taxpayer_blind_63_f_2_A_in:
      ((money * code_location)) Optional.t;
    additional_amount_spouse_blind_63_f_2_B_in:
      ((money * code_location)) Optional.t;
    additional_standard_deduction_63_c_3_in:
      ((money * code_location)) Optional.t;
    basic_standard_deduction_63_c_2_before_c_5_in:
      ((money * code_location)) Optional.t;
    standard_deduction_eligible_63_c_6_in:
      ((bool * code_location)) Optional.t;
    standard_deduction_63_c_1_in:
      ((money * code_location)) Optional.t;
    taxable_income_in:
      ((money * code_location)) Optional.t
  }
end

module IndividualTaxReturnSection68ItemizedDeductions_in : sig
  type t = {
    individual_tax_return_in:
      IndividualTaxReturn.t;
    adjusted_gross_income_in: money;
    itemized_deductions_in: money;
    taxpayer_marital_status_in:
      IndividualSection7703MaritalStatusOutput.t;
    is_surviving_spouse_in: bool;
    is_head_of_household_in: bool;
    applicable_amount_68_b_1_in:
      ((money * code_location)) Optional.t;
    three_percent_reduction_68_a_1_in:
      ((money * code_location)) Optional.t;
    eighty_percent_reduction_68_a_2_in:
      ((money * code_location)) Optional.t;
    reduction_amount_68_a_in:
      ((money * code_location)) Optional.t;
    itemized_deductions_after_68_in:
      ((money * code_location)) Optional.t;
    section_not_applicable_68_f_in:
      ((bool * code_location)) Optional.t
  }
end

module IndividualSection151ExemptionsList_in : sig
  type t = {
    individual_in: Individual.t;
    spouse_in: (Individual.t) Optional.t;
    tax_year_in: integer;
    tax_return_events_in: TaxReturnEvent.t array;
    income_events_in: IncomeEvent.t array;
    dependents_in: Individual.t array;
    is_joint_or_surviving_spouse_in: bool;
    spouse_personal_exemption_allowed_in:
      ((bool * code_location)) Optional.t;
    individuals_entitled_to_exemptions_under_151_in:
      (((Individual.t array) * code_location)) Optional.t
  }
end

module TaxpayerExemptionsList151_in : sig
  type t = {
    individual_tax_return_in:
      IndividualTaxReturn.t;
    tax_return_events_in: TaxReturnEvent.t array;
    income_events_in: IncomeEvent.t array;
    dependents_in: Individual.t array;
    spouse_result_in:
      (((IndividualSection151ExemptionsListOutput.t) Optional.t
         * code_location)) Optional.t;
    individuals_entitled_to_exemptions_under_151_in:
      (((Individual.t array) * code_location)) Optional.t;
    spouse_personal_exemption_allowed_in:
      ((bool * code_location)) Optional.t
  }
end

module IndividualSection151PersonalExemption_in : sig
  type t = {
    individual_in: Individual.t;
    individual_tax_return_in:
      IndividualTaxReturn.t;
    tax_year_in: integer;
    tax_return_events_in: TaxReturnEvent.t array;
    adjusted_gross_income_in: money;
    applicable_amount_in: money;
    all_individuals_entitled_to_exemptions_under_151_in:
      Individual.t array;
    exemption_amount_base_in:
      ((money * code_location)) Optional.t;
    number_of_personal_exemptions_151_c_in:
      ((integer * code_location)) Optional.t;
    personal_exemptions_deduction_151_a_in:
      ((money * code_location)) Optional.t;
    applicable_percentage_151_d_3_B_in:
      ((decimal * code_location)) Optional.t;
    exemption_amount_zero_151_d_5_in:
      ((bool * code_location)) Optional.t
  }
end

module IndividualSection152Dependents_in : sig
  type t = {
    taxpayer_in: Individual.t;
    tax_year_in: integer;
    individuals_in: Individual.t array;
    family_relationship_events_in:
      FamilyRelationshipEvent.t array;
    birth_events_in: BirthEvent.t array;
    residence_period_events_in:
      ResidencePeriodEvent.t array;
    tax_return_events_in: TaxReturnEvent.t array;
    income_events_in: IncomeEvent.t array;
    marriage_events_in: MarriageEvent.t array;
    qualifying_children_in:
      (((IndividualSection152QualifyingChildOutput.t
         array) * code_location)) Optional.t;
    qualifying_relatives_in:
      (((IndividualSection152QualifyingRelativeOutput.t
         array) * code_location)) Optional.t;
    dependents_initial_in:
      (((Individual.t array) * code_location)) Optional.t;
    individual_dependent_statuses_in:
      (((IndividualDependentStatus.t array) *
         code_location)) Optional.t
  }
end

module IndividualSection152QualifyingChild_in : sig
  type t = {
    individual_in: Individual.t;
    taxpayer_in: Individual.t;
    tax_year_in: integer;
    family_relationship_events_in:
      FamilyRelationshipEvent.t array;
    birth_events_in: BirthEvent.t array;
    residence_period_events_in:
      ResidencePeriodEvent.t array;
    tax_return_events_in: TaxReturnEvent.t array;
    relationship_requirement_met_in:
      ((bool * code_location)) Optional.t;
    principal_place_of_abode_requirement_met_in:
      ((bool * code_location)) Optional.t;
    age_requirement_met_in:
      ((bool * code_location)) Optional.t;
    joint_return_exception_applies_in:
      ((bool * code_location)) Optional.t;
    is_qualifying_child_in:
      ((bool * code_location)) Optional.t
  }
end

module IndividualSection152QualifyingRelative_in : sig
  type t = {
    individual_in: Individual.t;
    taxpayer_in: Individual.t;
    tax_year_in: integer;
    family_relationship_events_in:
      FamilyRelationshipEvent.t array;
    residence_period_events_in:
      ResidencePeriodEvent.t array;
    qualifying_child_results_in:
      IndividualSection152QualifyingChildOutput.t
      array;
    tax_return_events_in: TaxReturnEvent.t array;
    income_events_in: IncomeEvent.t array;
    marriage_events_in: MarriageEvent.t array;
    relationship_requirement_met_H_in:
      ((bool * code_location)) Optional.t;
    relationship_requirement_met_in:
      ((bool * code_location)) Optional.t;
    no_income_requirement_met_in:
      ((bool * code_location)) Optional.t;
    not_qualifying_child_requirement_met_in:
      ((bool * code_location)) Optional.t;
    is_qualifying_relative_in:
      ((bool * code_location)) Optional.t
  }
end

module IndividualSection7703MaritalStatus_in : sig
  type t = {
    individual_in: Individual.t;
    tax_year_in: integer;
    marriage_events_in: MarriageEvent.t array;
    divorce_or_legal_separation_events_in:
      DivorceOrLegalSeparationEvent.t array;
    death_events_in: DeathEvent.t array;
    individual_tax_return_in:
      IndividualTaxReturn.t;
    residence_period_events_in:
      ResidencePeriodEvent.t array;
    household_maintenance_events_in:
      HouseholdMaintenanceEvent.t array;
    qualifying_children_in:
      IndividualSection152QualifyingChildOutput.t
      array;
    individuals_entitled_to_exemptions_under_151_in:
      Individual.t array;
    determination_date_in:
      ((date * code_location)) Optional.t;
    is_married_at_determination_date_in:
      ((bool * code_location)) Optional.t;
    is_legally_separated_in:
      ((bool * code_location)) Optional.t;
    households_with_qualifying_child_in:
      (((Household.t array) * code_location)) Optional.t;
    households_maintained_by_individual_in:
      (((Household.t array) * code_location)) Optional.t;
    spouse_not_member_of_household_last_6_months_in:
      ((bool * code_location)) Optional.t;
    subsection_b_exception_applies_in:
      ((bool * code_location)) Optional.t;
    is_married_for_tax_purposes_in:
      ((bool * code_location)) Optional.t;
    maintains_household_with_qualifying_child_for_more_than_half_year_in:
      ((bool * code_location)) Optional.t;
    furnishes_over_one_half_of_household_cost_in:
      ((bool * code_location)) Optional.t
  }
end

module OrganizationSection3306EmployerStatus_in : sig
  type t = {
    organization_in: Organization.t;
    calendar_year_in: integer;
    wage_payment_events_in:
      WagePaymentEvent.t array;
    employment_relationship_events_in:
      EmploymentRelationshipEvent.t array;
    is_general_employer_in:
      ((bool * code_location)) Optional.t;
    is_agricultural_employer_in:
      ((bool * code_location)) Optional.t;
    is_domestic_service_employer_in:
      ((bool * code_location)) Optional.t;
    is_employer_in:
      ((bool * code_location)) Optional.t
  }
end

module WagePaymentEventSection3306Wages_in : sig
  type t = {
    wage_payment_event_in: WagePaymentEvent.t;
    employment_termination_events_in:
      EmploymentTerminationEvent.t array;
    death_events_in: DeathEvent.t array;
    is_excluded_by_sickness_disability_death_in:
      ((bool * code_location)) Optional.t;
    is_excluded_by_nonbusiness_service_in:
      ((bool * code_location)) Optional.t;
    is_excluded_by_termination_payment_in:
      ((bool * code_location)) Optional.t;
    is_excluded_by_agricultural_noncash_in:
      ((bool * code_location)) Optional.t;
    is_excluded_by_survivor_payment_in:
      ((bool * code_location)) Optional.t;
    taxable_amount_before_7000_cap_in:
      ((money * code_location)) Optional.t
  }
end

module TotalWages3306Calculation_in : sig
  type t = {
    wage_results_in:
      WagePaymentEventSection3306WagesOutput.t
      array;
    total_taxable_wages_in:
      ((money * code_location)) Optional.t
  }
end

module EmploymentRelationshipEventSection3306Employment_in : sig
  type t = {
    employment_relationship_event_in:
      EmploymentRelationshipEvent.t;
    calendar_year_in: integer;
    wage_payment_events_in:
      WagePaymentEvent.t array;
    employment_relationship_events_in:
      EmploymentRelationshipEvent.t array;
    student_enrollment_events_in:
      StudentEnrollmentEvent.t array;
    hospital_patient_events_in:
      HospitalPatientEvent.t array;
    immigration_admission_events_in:
      ImmigrationAdmissionEvent.t array;
    parenthood_events_in: ParenthoodEvent.t array;
    birth_events_in: BirthEvent.t array;
    marriage_events_in: MarriageEvent.t array;
    employer_status_in:
      ((OrganizationSection3306EmployerStatusOutput.t
         * code_location)) Optional.t;
    is_excluded_agricultural_labor_in:
      ((bool * code_location)) Optional.t;
    is_excluded_domestic_service_in:
      ((bool * code_location)) Optional.t;
    is_excluded_family_employment_in:
      ((bool * code_location)) Optional.t;
    is_excluded_federal_government_in:
      ((bool * code_location)) Optional.t;
    is_excluded_state_government_in:
      ((bool * code_location)) Optional.t;
    is_excluded_student_service_in:
      ((bool * code_location)) Optional.t;
    is_excluded_hospital_patient_service_in:
      ((bool * code_location)) Optional.t;
    is_excluded_foreign_government_in:
      ((bool * code_location)) Optional.t;
    is_excluded_student_nurse_in:
      ((bool * code_location)) Optional.t;
    is_excluded_international_organization_in:
      ((bool * code_location)) Optional.t;
    is_excluded_penal_institution_in:
      ((bool * code_location)) Optional.t;
    is_employment_in:
      ((bool * code_location)) Optional.t
  }
end

module EmployerUnemploymentExciseTaxFilerSection3301Tax_in : sig
  type t = {
    employer_unemployment_excise_tax_return_in:
      EmployerUnemploymentExciseTaxReturn.t;
    wage_payment_wages_results_in:
      WagePaymentEventSection3306WagesOutput.t
      array;
    organization_employer_statuses_in:
      OrganizationSection3306EmployerStatusOutput.t
      array;
    employment_relationship_employment_results_in:
      EmploymentRelationshipEventSection3306EmploymentOutput.t
      array;
    total_taxable_wages_in:
      ((money * code_location)) Optional.t;
    excise_tax_in:
      ((money * code_location)) Optional.t;
    tax_rate_in:
      ((decimal * code_location)) Optional.t
  }
end

module IRCSimplified_in : sig
  type t = {
    individual_tax_return_in:
      IndividualTaxReturn.t;
    individuals_in: Individual.t array;
    organizations_in: Organization.t array;
    birth_events_in: BirthEvent.t array;
    blindness_status_events_in:
      BlindnessStatusEvent.t array;
    death_events_in: DeathEvent.t array;
    nonresident_alien_status_period_events_in:
      NonresidentAlienStatusPeriodEvent.t array;
    marriage_events_in: MarriageEvent.t array;
    divorce_or_legal_separation_events_in:
      DivorceOrLegalSeparationEvent.t array;
    residence_period_events_in:
      ResidencePeriodEvent.t array;
    household_maintenance_events_in:
      HouseholdMaintenanceEvent.t array;
    parenthood_events_in: ParenthoodEvent.t array;
    family_relationship_events_in:
      FamilyRelationshipEvent.t array;
    tax_return_events_in: TaxReturnEvent.t array;
    income_events_in: IncomeEvent.t array;
    employment_relationship_events_in:
      EmploymentRelationshipEvent.t array;
    wage_payment_events_in:
      WagePaymentEvent.t array;
    student_enrollment_events_in:
      StudentEnrollmentEvent.t array;
    hospital_patient_events_in:
      HospitalPatientEvent.t array;
    immigration_admission_events_in:
      ImmigrationAdmissionEvent.t array;
    employment_termination_events_in:
      EmploymentTerminationEvent.t array;
    employer_unemployment_excise_tax_return_in:
      EmployerUnemploymentExciseTaxReturn.t;
    taxable_income_in:
      ((money * code_location)) Optional.t;
    itemized_deductions_in:
      ((money * code_location)) Optional.t;
    adjusted_gross_income_in:
      ((money * code_location)) Optional.t;
    taxable_income_result_in:
      ((IndividualTaxReturnSection63TaxableIncomeOutput.t
         * code_location)) Optional.t;
    tax_in: ((money * code_location)) Optional.t;
    is_surviving_spouse_in:
      ((bool * code_location)) Optional.t;
    is_head_of_household_in:
      ((bool * code_location)) Optional.t;
    section_2a_surviving_spouse_result_in:
      ((IndividualTaxReturnSection2aSurvivingSpouseOutput.t
         * code_location)) Optional.t;
    section_2b_head_of_household_result_in:
      ((IndividualTaxReturnSection2bHeadOfHouseholdOutput.t
         * code_location)) Optional.t;
    itemized_deductions_result_in:
      ((IndividualTaxReturnSection68ItemizedDeductionsOutput.t
         * code_location)) Optional.t;
    taxpayer_exemptions_list_result_in:
      ((TaxpayerExemptionsList151Output.t *
         code_location)) Optional.t;
    taxpayer_exemption_result_in:
      ((IndividualSection151PersonalExemptionOutput.t
         * code_location)) Optional.t;
    tax_imposed_result_in:
      ((IndividualTaxReturnSection1TaxOutput.t *
         code_location)) Optional.t;
    taxpayer_dependents_result_in:
      ((IndividualSection152DependentsOutput.t *
         code_location)) Optional.t;
    taxpayer_marital_status_7703_in:
      ((IndividualSection7703MaritalStatusOutput.t
         * code_location)) Optional.t;
    organization_employer_statuses_in:
      (((OrganizationSection3306EmployerStatusOutput.t
         array) * code_location)) Optional.t;
    wage_payment_wages_results_in:
      (((WagePaymentEventSection3306WagesOutput.t
         array) * code_location)) Optional.t;
    employment_relationship_employment_results_in:
      (((EmploymentRelationshipEventSection3306EmploymentOutput.t
         array) * code_location)) Optional.t;
    employer_unemployment_excise_tax_result_in:
      ((EmployerUnemploymentExciseTaxFilerSection3301TaxOutput.t
         * code_location)) Optional.t
  }
end


(** Scope IndividualTaxReturnSection1Tax *)
val individual_tax_return_section1_tax :
  IndividualTaxReturnSection1Tax_in.t ->
  IndividualTaxReturnSection1Tax.t

(** Scope IndividualSection151ExemptionsList *)
val individual_section151_exemptions_list :
  IndividualSection151ExemptionsList_in.t ->
  IndividualSection151ExemptionsList.t

(** Scope IndividualSection152QualifyingRelative *)
val individual_section152_qualifying_relative :
  IndividualSection152QualifyingRelative_in.t ->
  IndividualSection152QualifyingRelative.t

(** Scope OrganizationSection3306EmployerStatus *)
val organization_section3306_employer_status :
  OrganizationSection3306EmployerStatus_in.t ->
  OrganizationSection3306EmployerStatus.t

(** Scope WagePaymentEventSection3306Wages *)
val wage_payment_event_section3306_wages :
  WagePaymentEventSection3306Wages_in.t ->
  WagePaymentEventSection3306Wages.t

(** Scope TotalWages3306Calculation *)
val total_wages3306_calculation :
  TotalWages3306Calculation_in.t ->
  TotalWages3306Calculation.t

(** Toplevel definition get_year_end *)
val get_year_end : integer -> date

(** Toplevel definition get_taxpayer *)
val get_taxpayer : IndividualTaxReturn.t ->
                     Individual.t

(** Toplevel definition get_spouse *)
val get_spouse : IndividualTaxReturn.t ->
                   (Individual.t) Optional.t

(** Toplevel definition is_tax_year_2018_through_2025 *)
val is_tax_year_2018_through_2025 : integer ->
                                      bool

(** Toplevel definition get_last_spouse_from_marriage_events *)
val get_last_spouse_from_marriage_events : Individual.t ->
                                             (MarriageEvent.t
                                              array) ->
                                             date ->
                                             (Individual.t) Optional.t

(** Toplevel definition period_spans_more_than_half_year *)
val period_spans_more_than_half_year : date ->
                                         date ->
                                         integer ->
                                         bool

(** Scope EmploymentRelationshipEventSection3306Employment *)
val employment_relationship_event_section3306_employment :
  EmploymentRelationshipEventSection3306Employment_in.t ->
  EmploymentRelationshipEventSection3306Employment.t

(** Scope EmployerUnemploymentExciseTaxFilerSection3301Tax *)
val employer_unemployment_excise_tax_filer_section3301_tax :
  EmployerUnemploymentExciseTaxFilerSection3301Tax_in.t ->
  EmployerUnemploymentExciseTaxFilerSection3301Tax.t

(** Scope TaxpayerExemptionsList151 *)
val taxpayer_exemptions_list151 :
  TaxpayerExemptionsList151_in.t ->
  TaxpayerExemptionsList151.t

(** Scope IndividualTaxReturnSection2aSurvivingSpouse *)
val individual_tax_return_section2a_surviving_spouse :
  IndividualTaxReturnSection2aSurvivingSpouse_in.t ->
  IndividualTaxReturnSection2aSurvivingSpouse.t

(** Scope IndividualSection151PersonalExemption *)
val individual_section151_personal_exemption :
  IndividualSection151PersonalExemption_in.t ->
  IndividualSection151PersonalExemption.t

(** Scope IndividualTaxReturnSection68ItemizedDeductions *)
val individual_tax_return_section68_itemized_deductions :
  IndividualTaxReturnSection68ItemizedDeductions_in.t ->
  IndividualTaxReturnSection68ItemizedDeductions.t

(** Scope IndividualTaxReturnSection63TaxableIncome *)
val individual_tax_return_section63_taxable_income :
  IndividualTaxReturnSection63TaxableIncome_in.t ->
  IndividualTaxReturnSection63TaxableIncome.t

(** Scope IndividualSection7703MaritalStatus *)
val individual_section7703_marital_status :
  IndividualSection7703MaritalStatus_in.t ->
  IndividualSection7703MaritalStatus.t

(** Scope IndividualSection152QualifyingChild *)
val individual_section152_qualifying_child :
  IndividualSection152QualifyingChild_in.t ->
  IndividualSection152QualifyingChild.t

(** Scope IndividualSection152Dependents *)
val individual_section152_dependents :
  IndividualSection152Dependents_in.t ->
  IndividualSection152Dependents.t

(** Scope IndividualTaxReturnSection2bHeadOfHousehold *)
val individual_tax_return_section2b_head_of_household :
  IndividualTaxReturnSection2bHeadOfHousehold_in.t ->
  IndividualTaxReturnSection2bHeadOfHousehold.t

(** Scope IRCSimplified *)
val i_r_c_simplified :
  IRCSimplified_in.t -> IRCSimplified.t
